version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "feed-back-number"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1sf0mvevz8ngb"
s3_prefix = "feed-back-number"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "BucketName=\"feed-back-number\""
image_repositories = []
